# Generated by Django 5.2 on 2025-06-04 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_account',
            field=models.OneToOneField(blank=True, help_text='Linked portal user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to='patient_portal.patientuser'),
        ),
    ]
