# Generated by Django 5.2 on 2025-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_account',
        ),
    ]
