from django.contrib import admin
from .models import Report

@admin.register(Report)
class ReportAdmin(admin.ModelAdmin):
    list_display = ('id', 'report_type', 'start_date', 'end_date', 'display_generator', 'created_at', 'format')
    list_filter = ('report_type', 'format', 'created_at')
    search_fields = ('generated_by_user__username', 'generated_by_user__first_name',
                    'generated_by_user__last_name', 'start_date', 'end_date')
    date_hierarchy = 'created_at'
    readonly_fields = ('created_at', 'display_generator')
    list_per_page = 20

    fieldsets = (
        ('Report Information', {
            'fields': ('report_type', 'format', 'file')
        }),
        ('Date Information', {
            'fields': ('start_date', 'end_date')
        }),
        ('User Information', {
            'fields': ('generated_by_user', 'created_at', 'display_generator')
        }),
        ('Options', {
            'fields': ('include_details', 'group_by_department')
        }),
    )

    def display_generator(self, obj):
        return obj.generator_display  # Use the model's safe property

    display_generator.short_description = 'Generated By'