# Generated by Django 5.2 on 2025-04-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('processing_days', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_date', models.DateTimeField()),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('reported', 'Reported'), ('archived', 'Archived')], default='collected', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='patients.patient')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.sampletype')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
    ]
