# Generated by Django 5.2 on 2025-06-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sample_paid_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='paid',
        ),
        migrations.AddField(
            model_name='sample',
            name='current_technician',
            field=models.ForeignKey(blank=True, help_text='Technician currently handling the sample', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Additional details about rejection', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('hemolyzed', 'Hemolyzed'), ('insufficient', 'Insufficient Volume'), ('contaminated', 'Contaminated'), ('mislabeled', 'Mislabeled'), ('expired', 'Expired'), ('other', 'Other')], help_text='Reason for sample rejection', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('reported', 'Reported'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='collected', help_text='Current status of the sample in the workflow', max_length=20),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('samples', models.ManyToManyField(limit_choices_to={'status__in': ['collected', 'received']}, related_name='batches', to='samples.sample')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('from_technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='samples.sample')),
                ('to_technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custody Log',
                'verbose_name_plural': 'Custody Logs',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
