# Generated by Django 5.2 on 2025-04-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('template_name', models.CharField(default='default', max_length=100)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='results.result')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
