# Generated by Django 5.2 on 2025-06-25 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='result',
        ),
        migrations.RemoveField(
            model_name='report',
            name='template_name',
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generated by (User)'),
        ),
        migrations.AddField(
            model_name='report',
            name='group_by_department',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='include_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('results', 'Results Report'), ('activity', 'Activity Report'), ('performance', 'Performance Report')], default='results', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.CharField(blank=True, default='Unknown', max_length=100, verbose_name='Generated by (Text)'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by_user'], name='reports_rep_generat_5c1894_idx'),
        ),
    ]
