# Generated by Django 5.2 on 2025-06-25 19:24
from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_remove_report_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_by_user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                related_name='generated_reports',
                to=settings.AUTH_USER_MODEL,
                verbose_name="Generated by (User)"
            ),
        ),
    ]