# Generated by Django 5.2 on 2025-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_bill_pdf_file_alter_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/pdfs/', verbose_name='PDF Document'),
        ),
    ]
