# Generated by Django 5.2 on 2025-06-28 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_pdf_file'),
        ('patients', '0003_remove_patient_user_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax Amount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bills/qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='billing_bil_status_ddee07_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['issued_date'], name='billing_bil_issued__19e153_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['patient'], name='billing_bil_patient_2ca142_idx'),
        ),
    ]
