# Generated by Django 5.2 on 2025-06-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='sample_types',
            field=models.ManyToManyField(related_name='analysis_types', to='samples.sampletype'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.analysistype'),
        ),
    ]
