# Generated by Django 5.2 on 2025-06-19 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('samples', '0004_alter_batch_options_alter_custodylog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysis',
            name='analysis_an_sample__393818_idx',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='analysis_type',
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['sample'], name='analysis_an_sample__9c4711_idx'),
        ),
    ]
