# Generated by Django 5.2 on 2025-06-19 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_analysis_analysis_an_sample__393818_idx_and_more'),
        ('samples', '0004_alter_batch_options_alter_custodylog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='analysis.analysistype'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine (7-10 hours)'), ('urgent', 'Urgent (4 hours)'), ('stat', 'STAT (<1 hour)')], default='routine', max_length=20),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['analysis_type'], name='analysis_an_analysi_4fa0a4_idx'),
        ),
    ]
