# Generated by Django 5.2 on 2025-06-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysis_analysis_type_alter_analysis_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(help_text='Original equipment output')),
                ('formatted_data', models.JSONField(help_text='Human-readable formatted results')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('test_code', models.CharField(blank=True, max_length=20)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysis')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id'], name='analysis_an_patient_273895_idx'), models.Index(fields=['test_code'], name='analysis_an_test_co_56cb27_idx')],
            },
        ),
    ]
