# Generated by Django 5.2 on 2025-06-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
        ('analysis', '0003_auto_20250613_1206'),
    ]

    operations = [
    ]
