# Generated by Django 5.2 on 2025-06-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
