# Generated by Django 5.2 on 2025-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_merge_0002_initial_0003_auto_20250613_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat')], default='routine', max_length=20),
        ),
    ]
