# Generated by Django 5.2 on 2025-06-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysisresult_options_and_more'),
        ('billing', '0002_remove_bill_pdf_file_alter_bill_amount_and_more'),
        ('samples', '0004_alter_batch_options_alter_custodylog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='billing.bill'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['bill'], name='analysis_an_bill_id_b99fcb_idx'),
        ),
    ]
