# Generated by Django 5.2 on 2025-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_due_date_analysis_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='selected_panels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='blood_panels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='category',
            field=models.CharField(choices=[('blood', 'Blood Analysis'), ('urine', 'Urine Analysis'), ('tissue', 'Tissue Analysis'), ('molecular', 'Molecular Analysis')], default='blood', max_length=20),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='is_blood_panel',
            field=models.BooleanField(default=False),
        ),
    ]
