# Generated by Django 5.2 on 2025-07-01 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_batchanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchanalysis',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchanalysis',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='batchanalysis',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='batchanalysis',
            name='technician',
        ),
        migrations.AddField(
            model_name='batchanalysis',
            name='analyses',
            field=models.ManyToManyField(related_name='batches', to='analysis.analysis'),
        ),
        migrations.AddField(
            model_name='batchanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
