# Generated by Django 5.2 on 2025-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('samples_processed', models.IntegerField(default=0)),
                ('avg_processing_time', models.FloatField(help_text='In hours')),
                ('critical_results', models.IntegerField(default=0)),
            ],
        ),
    ]
