# Generated by Django 5.2 on 2025-06-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysisresult_options_and_more'),
        ('analytics', '0001_initial'),
        ('samples', '0004_alter_batch_options_alter_custodylog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnaroundTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_to_receipt_hours', models.FloatField()),
                ('receipt_to_result_hours', models.FloatField()),
                ('total_hours', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
            ],
            options={
                'indexes': [models.Index(fields=['total_hours'], name='analytics_t_total_h_0df3d0_idx')],
            },
        ),
    ]
